service: sns-api

frameworkVersion: '2'

package:
  patterns:
    - '!node_modules/**'
    - '!assets/**'

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  region: 'eu-west-2' # London
  lambdaHashingVersion: 20201221
  apiKeys:
    - snsKey
  iam: 
    role: 
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "sns:*"
functions:
  hello:
    handler: handlers.hello
    events:
      - http:
          path: hello
          method: post
          cors: true
  sns-create-topic:
    handler: sns.createTopic
    events:
      - http:
          path: sns/topic
          method: post
          private: true
          cors: true
  sns-subscribe-to-topic:
    handler: sns.subscribeToTopic
    events:
      - http:
          path: sns/subscribe
          method: post
          private: true
          cors: true
  sns-publish-message:
    handler: sns.publishMessage
    events:
      - http:
          path: sns/publish
          method: post
          private: true
          cors: true
