service: sns-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  region: 'eu-west-2' # London
  lambdaHashingVersion: 20201221
# TODO : 1. set SNS permissions
functions:
  # TODO : 2. add an api path  
  hello:
    handler: handlers.hello
    events:
      - http:
          path: hello
          method: post
          cors: true
  # TODO : 3. setup SNS function 
